/**
 * commands/scaffold.ts — `pyhall scaffold`
 *
 * Interactive worker scaffold wizard using inquirer.
 * Generates: worker.ts stub, registry-record.json, README.md
 */

import * as fs from 'fs';
import * as path from 'path';
import { searchCatalog, Entity } from '../catalog.js';
import { theme } from '../theme.js';

// Lazy import inquirer to avoid issues in test environments
async function getInquirer() {
  const { default: inquirer } = await import('inquirer');
  return inquirer;
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

function workerTemplate(opts: {
  capabilityId: string;
  guarantee: string;
  description: string;
  workerName: string;
}): string {
  const className = opts.workerName
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

  return `/**
 * ${opts.workerName} — WCP Worker
 *
 * Capability: ${opts.capabilityId}
 * Guarantee:  ${opts.guarantee}
 * Description: ${opts.description}
 *
 * Generated by pyhall scaffold — https://pyhall.dev
 */

export interface WorkerContext {
  correlation_id: string;
  tenant_id: string;
  env: 'dev' | 'staging' | 'prod';
  data_label: string;
  qos_class: string;
  capability_id: string;
}

export interface WorkerResultEnvelope<T = unknown> {
  status: 'ok' | 'err' | 'partial';
  data?: T;
  error?: string;
  metadata?: Record<string, unknown>;
}

export class ${className} {
  /**
   * Main worker entry point.
   *
   * @param ctx - Worker context (correlation ID, tenant, env, etc.)
   * @param request - Request payload
   * @returns WorkerResultEnvelope
   */
  async run(
    ctx: WorkerContext,
    request: Record<string, unknown>
  ): Promise<WorkerResultEnvelope> {
    // TODO: implement worker logic
    console.log(\`[\${ctx.correlation_id}] ${className}.run() — \${ctx.capability_id}\`);

    return {
      status: 'ok',
      data: {},
      metadata: {
        correlation_id: ctx.correlation_id,
        capability_id: ctx.capability_id,
        tenant_id: ctx.tenant_id,
        env: ctx.env,
        processed_at: new Date().toISOString(),
      },
    };
  }
}
`;
}

function registryRecordTemplate(opts: {
  capabilityId: string;
  guarantee: string;
  description: string;
  workerName: string;
}): string {
  const record = {
    wcp_version: '0.1',
    worker_species_id: `wrk.custom.${opts.workerName}`,
    name: opts.workerName,
    description: opts.description,
    handles_capabilities: [opts.capabilityId],
    guarantee: opts.guarantee,
    generated_by: 'pyhall scaffold',
    generated_at: new Date().toISOString(),
    spec: 'https://pyhall.dev/spec',
  };
  return JSON.stringify(record, null, 2);
}

function readmeTemplate(opts: {
  capabilityId: string;
  guarantee: string;
  description: string;
  workerName: string;
}): string {
  return `# ${opts.workerName}

${opts.description}

## WCP Worker Card

| Field | Value |
|-------|-------|
| Capability | \`${opts.capabilityId}\` |
| Delivery guarantee | \`${opts.guarantee}\` |
| Generated by | pyhall scaffold |

## Usage

\`\`\`typescript
import { ${opts.workerName.charAt(0).toUpperCase() + opts.workerName.slice(1)} } from './worker';

const worker = new ${opts.workerName.charAt(0).toUpperCase() + opts.workerName.slice(1)}();

const result = await worker.run(
  {
    correlation_id: 'your-correlation-id',
    tenant_id: 'your-tenant',
    env: 'dev',
    data_label: 'PUBLIC',
    qos_class: 'P2',
    capability_id: '${opts.capabilityId}',
  },
  { /* your request payload */ }
);

console.log(result);
\`\`\`

## References

- [pyhall.dev](https://pyhall.dev)
- [WCP Spec](https://pyhall.dev/spec)
- [Capability: ${opts.capabilityId}](https://pyhall.dev/taxonomy/${opts.capabilityId})
`;
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export async function runScaffold(): Promise<void> {
  const inquirer = await getInquirer();

  console.log('');
  console.log(theme.primary.bold('  pyhall scaffold') + theme.dim(' — Worker wizard'));
  console.log(theme.dim('  ' + '─'.repeat(60)));
  console.log('');

  // Step 1: description
  const { description } = await inquirer.prompt<{ description: string }>([
    {
      type: 'input',
      name: 'description',
      message: 'What does this worker do?',
      validate: (v: string) => v.trim().length > 3 || 'Please describe the worker',
    },
  ]);

  // Step 2: search taxonomy for matching capabilities
  const matches = searchCatalog(description, 8).filter(
    (r) => r.entity.type === 'capability' || r.entity.type === 'worker_species'
  );

  let capabilityId: string;

  if (matches.length > 0) {
    console.log('');
    console.log(theme.dim('  Matching taxonomy entities:'));
    const choices = [
      ...matches.map((m) => ({
        name: `${m.entity.id}  ${theme.dim(m.entity.name ?? '')}`,
        value: m.entity.id,
      })),
      { name: theme.dim('Enter custom capability ID'), value: '__custom__' },
    ];

    const { selectedId } = await inquirer.prompt<{ selectedId: string }>([
      {
        type: 'list',
        name: 'selectedId',
        message: 'Select capability ID:',
        choices,
      },
    ]);

    if (selectedId === '__custom__') {
      const { customId } = await inquirer.prompt<{ customId: string }>([
        {
          type: 'input',
          name: 'customId',
          message: 'Capability ID (e.g. cap.doc.classify):',
          validate: (v: string) => v.trim().length > 3 || 'Please enter a capability ID',
        },
      ]);
      capabilityId = customId.trim();
    } else {
      capabilityId = selectedId;
    }
  } else {
    const { customId } = await inquirer.prompt<{ customId: string }>([
      {
        type: 'input',
        name: 'customId',
        message: 'Capability ID (e.g. cap.doc.classify.v1):',
        validate: (v: string) => v.trim().length > 3 || 'Please enter a capability ID',
      },
    ]);
    capabilityId = customId.trim();
  }

  // Step 3: delivery guarantee
  const { guarantee } = await inquirer.prompt<{ guarantee: string }>([
    {
      type: 'list',
      name: 'guarantee',
      message: 'Delivery guarantee:',
      choices: [
        { name: 'best-effort      (fire and forget)', value: 'best-effort' },
        { name: 'at-least-once    (retry until ack)', value: 'at-least-once' },
        { name: 'exactly-once     (idempotent, dedup required)', value: 'exactly-once' },
      ],
    },
  ]);

  // Step 4: worker name
  const suggestedName = capabilityId
    .replace(/^cap\./, '')
    .replace(/\.v\d+$/, '')
    .replace(/\./g, '-')
    .toLowerCase();

  const { workerName } = await inquirer.prompt<{ workerName: string }>([
    {
      type: 'input',
      name: 'workerName',
      message: 'Worker name (snake-case):',
      default: suggestedName,
      validate: (v: string) => /^[a-z0-9-]+$/.test(v.trim()) || 'Use lowercase letters, digits, hyphens',
    },
  ]);

  // Step 5: output directory
  const { outputDir } = await inquirer.prompt<{ outputDir: string }>([
    {
      type: 'input',
      name: 'outputDir',
      message: 'Output directory:',
      default: `./${workerName}`,
    },
  ]);

  // Generate files
  const resolvedDir = path.resolve(outputDir.trim());
  const opts = {
    capabilityId,
    guarantee,
    description: description.trim(),
    workerName: workerName.trim(),
  };

  console.log('');

  if (!fs.existsSync(resolvedDir)) {
    fs.mkdirSync(resolvedDir, { recursive: true });
  }

  const files = [
    { name: 'worker.ts',             content: workerTemplate(opts) },
    { name: 'registry-record.json',  content: registryRecordTemplate(opts) },
    { name: 'README.md',             content: readmeTemplate(opts) },
  ];

  for (const file of files) {
    const filePath = path.join(resolvedDir, file.name);
    fs.writeFileSync(filePath, file.content, 'utf8');
    console.log(`  ${theme.success('created')}  ${filePath}`);
  }

  console.log('');
  console.log(theme.primary.bold('  Worker scaffold complete.'));
  console.log('');
  console.log(`  ${theme.dim('Capability:')}   ${capabilityId}`);
  console.log(`  ${theme.dim('Guarantee:')}    ${guarantee}`);
  console.log(`  ${theme.dim('Output:')}       ${resolvedDir}`);
  console.log('');
  console.log(theme.dim('  Next steps:'));
  console.log(theme.dim(`    1. Implement run() in ${path.join(resolvedDir, 'worker.ts')}`));
  console.log(theme.dim(`    2. Register the worker in your workforce registry`));
  console.log(theme.dim(`    3. See https://pyhall.dev/docs/workers for WCP worker guide`));
  console.log('');
}
